// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cmo, toplevel=false, use-js-string=true, version=6.4.1

//# unitInfo: Provides: Dune__exe__Main
//# unitInfo: Requires: Js_of_ocaml__Dom_html, Js_of_ocaml__Js
//# shape: Dune__exe__Main:[]
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    Js_of_ocaml_Dom_html = runtime.caml_get_global("Js_of_ocaml__Dom_html"),
    t0 = Js_of_ocaml_Dom_html[8];
   t0.alert("Hello from jaksho!");
   runtime.caml_register_global([0], "Dune__exe__Main");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLm1haW4uZW9ianMvanNvby9kdW5lX19leGVfX01haW4uY21vLmpzIiwic2VjdGlvbnMiOlt7Im9mZnNldCI6eyJsaW5lIjoxMCwiY29sdW1uIjowfSwibWFwIjp7InZlcnNpb24iOjMsImZpbGUiOiIubWFpbi5lb2Jqcy9qc29vL2R1bmVfX2V4ZV9fTWFpbi5jbW8uanMiLCJzb3VyY2VzIjpbIi9idWlsdGluL2JsYWNrYm94Lm1sIiwiL3dvcmtzcGFjZV9yb290L21haW4ubWwiXSwic291cmNlc0NvbnRlbnQiOlsiKCogZ2VuZXJhdGVkIGNvZGUgKikiLCJvcGVuIEpzX29mX29jYW1sXG5cblxubGV0ICgpID1cblx0bGV0IG1lc3NhZ2UgPSBKcy5zdHJpbmcgXCJIZWxsbyBmcm9tIGpha3NobyFcIiBpblxuXHREb21faHRtbC53aW5kb3cjI2FsZXJ0IG1lc3NhZ2UiXSwibmFtZXMiOlsicnVudGltZSIsIkpzX29mX29jYW1sX0RvbV9odG1sIiwidDAiXSwibWFwcGluZ3MiOiJJQUFBQSxVQUFBO0FBQUEsSUFBQUMsdUJBQUE7QUFBQSxJQUFBQyxLQ0tDO0FBQUE7QUFBQSxHQUE4QjtBQUFBO0FBQUEsRURML0IiLCJpZ25vcmVMaXN0IjpbMF19fV19
